version: '3.8'

services:
  api:
    environment:
      - DEBUG=True
      - LOG_LEVEL=INFO
    ports:
      - "8001:8000"  # Porta diferente para evitar conflito com outras versões
    volumes:
      - ./:/app
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.3'
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  worker:
    environment:
      - DEBUG=True
      - LOG_LEVEL=INFO
    volumes:
      - ./:/app
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    healthcheck:
      test: ["CMD", "celery", "-A", "app10.worker", "inspect", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    volumes:
      - postgres_data_staging:/var/lib/postgresql/data/
    ports:
      - "5433:5432"  # Porta diferente para evitar conflito

  redis:
    volumes:
      - redis_data_staging:/data
    ports:
      - "6380:6379"  # Porta diferente para evitar conflito

volumes:
  postgres_data_staging:
  redis_data_staging: 