version: '3.8'

services:
  # Serviço do banco de dados PostgreSQL
  db:
    image: postgres:13
    container_name: diagnostic-system-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=diagnostic_system_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Serviço do backend FastAPI
  backend:
    build: ./backend
    container_name: diagnostic-system-backend
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - model_data:/app/models
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/diagnostic_system_db
    ports:
      - "8000:8000"
    restart: always

  # Serviço do frontend React
  frontend:
    build: ./frontend
    container_name: diagnostic-system-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
    restart: always
    environment:
      - REACT_APP_API_URL=http://localhost:8000

volumes:
  postgres_data:
  model_data: 